### ISSUE TITLE
webpackConfig.modules must be webpackConfig.module

### ISSUE THREAD

**Issue by zowers** [suitupalex/requirejs-to-webpack-cli#7]
webpack config uses "module" array instead of "modules" see https://webpack.github.io/docs/configuration.html#module

all entries of "modules" must be replaced to "module"
https://github.com/suitupalex/requirejs-to-webpack-cli/search?q=modules

**Comment by pateketu** [comment]
Get a Syntax error
requirejs-to-webpack-cli config-require.js
undefined:54
});
  ^

SyntaxError: Unexpected token ;
    at handleRead (C:\Users\ketul.patel\AppData\Roaming\npm\node_modules\requirejs-to-webpack-cli\lib\parse.js:23:38)
    at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:380:3)

**Comment by mkontsek** [comment]
@pateketu I just started with this script, but I think you should put only the config object itself in the file you are trying to parse.

**Comment by pateketu** [comment]
Yes I tried that, here is my config object
Which gives following error
undefined:10
    paths: {
         ^

SyntaxError: Unexpected token :
    at handleRead (C:\Users\ketul.patel\AppData\Roaming\npm\node_modules\requirejs-to-webpack-cli\lib\parse.js:23:32)
    at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:380:3)

Here is the config object:

`{

```
// Define packages to use as path shortcuts to directories.
packages: [
    { name: 'core', location: 'app/core' },
    { name: 'layout', location: 'app/layout' },
    { name: 'layoutComponents', location: 'app/layout/components' },
    { name: 'templates', location: 'app/template-components' }
],

paths: {
    'jQuery': 'bower_components/jquery/dist/jquery',
    'underscore': 'bower_components/underscore/underscore-min',
    'angular': 'bower_components/angular/angular',
    'stringjs': 'bower_components/stringjs/dist/string.min',
    'moment': 'bower_components/moment/moment',
    'kendo.core.min': 'bower_components/kendo-ui/js/kendo.core.min',
    'kendo.all.min': 'bower_components/kendo-ui/js/kendo.all.min',
    'kendo.culture.en-GB.min': 'bower_components/kendo-ui/js/cultures/kendo.culture.en-GB.min',
    'ngCookies': 'bower_components/angular-cookies/angular-cookies.min',
    'uirouter': 'bower_components/angular-ui-router/release/angular-ui-router',
    'ngAnimate': 'bower_components/angular-animate/angular-animate',
    'app': 'app'
},

shim: {
    'jQuery': {
        exports: 'jQuery'
    },
    'underscore': {
        exports: '_'
    },
    'angular': {
        deps: ['jQuery'],
        exports: 'angular'
    },
    'kendo.all.min': {
        deps: ['jQuery', 'angular', 'kendo.core.min', 'kendo.culture.en-GB.min'],
        exports: 'kendo.all.min'
    },
    'ngCookies': {
        deps: ['angular'],
        exports: 'ngCookies'
    },
    'uirouter': {
        deps: ['angular'],
        exports: 'uirouter'
    },
    'ngAnimate': {
        deps: ['angular'],
        exports: 'ngAnimate'
    }
}
```

}`

**Comment by mkontsek** [comment]
I don't think 'packages' are supported, only 'modules'

**Comment by umamialex** [comment]
@zowers Sorry for taking so long to fix this, but it's done!

@pateketu Mind opening that as a separate issue? Through cursory research, It looks like it might be possible to convert RequireJS `packages` to `resolve.alias` with a bit of fiddling.
